force-app/main/default/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <label>List</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Place__c/List_Place__c.object-meta.xml
<CustomObject>
    <label>List Place</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>List Place Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Places</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Place__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>List</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>List Places</relationshipLabel>
    <relationshipName>List_Places</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Place__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Place</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>List Places</relationshipLabel>
    <relationshipName>List_Places</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyPlaces_Settings__c/MyPlaces_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MyPlaces Settings</label>
</CustomObject>

force-app/main/default/objects/MyPlaces_Settings__c/fields/Google_Places_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Google_Places_API_Key__c</fullName>
    <label>Google Places API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Place__c/Place__c.object-meta.xml
<CustomObject>
    <label>Place</label>
    <nameField>
        <label>Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestUtil.cls
@IsTest
public with sharing class TestUtil {
    @Future
    public static void insertAppUsers() {
        List<User> users = new List<User>();
        users.add(new User(
            ProfileId = AppConstants.APP_ADMIN_PROFILE.Id,
            Email = 'jdoe@test.com.invalid',
            Username = 'jdoe@myplaces.com',
            FirstName = 'John',
            LastName = 'Doe',
            Alias = 'jdoe',
            TimeZoneSidKey = 'Europe/Prague',
            LocaleSidKey = 'en_IE_EURO',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        ));
        users.add(new User(
            ProfileId = AppConstants.APP_USER_PROFILE.Id,
            Email = 'jrow@test.com.invalid',
            Username = 'jrow@myplaces.com',
            FirstName = 'Jane',
            LastName = 'Row',
            Alias = 'jrow',
            TimeZoneSidKey = 'Europe/Prague',
            LocaleSidKey = 'en_IE_EURO',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        ));
        insert users;
    }

    public static Place__c createPlace(Place__c template, Boolean isInsert) {
        Place__c place = template != null ? template.clone() : new Place__c();
        place.OwnerId = String.isNotBlank(place.OwnerId) ? place.OwnerId : UserInfo.getUserId();
        place.Name = String.isNotBlank(place.Name) ? place.Name : 'Test Place';

        if(isInsert) {
            insert place;
        }
        
        return place;
    }

    public static List__c createList(List__c template, Boolean isInsert) {
        List__c lst = template != null ? template.clone() : new List__c();
        lst.Name = String.isNotBlank(lst.Name) ? lst.Name : 'Test List';
        lst.Description__c = String.isNotBlank(lst.Description__c) ? lst.Description__c : 'List of the most awesome places';
        
        if(isInsert) {
            insert lst;
        }

        return lst;
    }

    public static List_Place__c createListPlace(List_Place__c template, Boolean isInsert) {
        List_Place__c lp = template != null ? template.clone() : new List_Place__c();
        String placeId = lp.Place__c;
        String listId = lp.List__c;

        if(String.isBlank(placeId) && String.isBlank(listId)) {
            Place__c p = createPlace(null, false);
            List__c l = createList(null, false);
            insert new List<SObject>{ p, l };
            lp.Place__c = p.Id;
            lp.List__c = l.Id;
        } else if(String.isBlank(placeId)) {
            Place__c p = createPlace(null, true);
            lp.Place__c = p.Id;
        } else if(String.isBlank(listId)) {
            List__c l = createList(null, true);
            lp.List__c = l.Id;
        }

        if(isInsert) {
            insert lp;
        }

        return lp;
    }

    public static void setupCustomSetting() {
        insert new MyPlaces_Settings__c(Google_Places_API_Key__c = 'a1b2c3');
    }
}