force-app/main/default/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <label>List</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Place__c/List_Place__c.object-meta.xml
<CustomObject>
    <label>List Place</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>List Place Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Places</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Place__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>List</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>List Places</relationshipLabel>
    <relationshipName>List_Places</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Place__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Place</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>List Places</relationshipLabel>
    <relationshipName>List_Places</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Place__c/Place__c.object-meta.xml
<CustomObject>
    <label>Place</label>
    <nameField>
        <label>Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddPlaceToListService.cls
public with sharing class AddPlaceToListService {
    @AuraEnabled
    public static List<List__c> getUserLists() {
        return [SELECT Id, Name FROM List__c WHERE OwnerId = :UserInfo.getUserId()];
    }

    @AuraEnabled
    public static List<List_Place__c> getListPlaces(String recordId) {
        return [SELECT Id, Place__c, List__c FROM List_Place__c WHERE Place__c = :recordId AND OwnerId = :UserInfo.getUserId()];
    }
}