force-app/main/default/objects/Feature_Setting__mdt/Feature_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Feature Setting</label>
    <pluralLabel>Feature Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Setting__mdt/fields/Properties_JSON__c.field-meta.xml
<CustomField>
    <fullName>Properties_JSON__c</fullName>
    <label>Properties JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TilesListService.cls
public with sharing class TilesListService {
    @AuraEnabled(cacheable = true)
    public static TilesListConfig getTilesListConfig(String contextName, String featureName) {
        TilesListConfig config;

        try {
            config = new TilesListConfig(contextName, featureName);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return config;
    }

    private static Map<String, Object> getConfig(String contextName, String featureName) {
        Map<String, Object> config;
        List<Feature_Setting__mdt> settings = [SELECT Properties_JSON__c FROM Feature_Setting__mdt WHERE DeveloperName = :featureName];

        if(!settings.isEmpty()) {
            Map<String, Object> setting = (Map<String, Object>)JSON.deserializeUntyped(settings[0].Properties_JSON__c);
            config = setting.containsKey(contextName) ? (Map<String, Object>)setting.get(contextName) : null;
        }

        return config;
    }

    public class TilesListConfig {
        @AuraEnabled
        public Map<String,Object> config;

        public TilesListConfig(String contextName, String featureName) {
            this.config = getConfig(contextName, featureName);
        }
    }
}